name: lens_spinner
description: Flutter widget to display a spinner similar to the spinner from the LENS application.
version: 0.0.1
homepage: https://github.com/grfc-ru/lens-spinner
repository: https://github.com/grfc-ru/lens-spinner/tree/main
issue_tracker: https://github.com/grfc-ru/lens-spinner/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
